on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt pyinstaller setuptools wheel importlib_metadata
      - run: pyinstaller --onefile src/main.py
      - run: mv dist/main catalyst
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          github_token: ${{ secrets.TOKEN }}
          asset_path: catalyst